# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - quality_check
  - test
  - security

variables:
  IMAGE: datakori/poetry
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/venv

quality_checks:
  stage: quality_check
  image: datakori/poetry

  before_script:
    - poetry config virtualenvs.in-project true

  script:
    - make quality

  cache:
    paths:
      - .venv

run_tests:
  stage: test
  image: $IMAGE
  script:
    - make test

security:
  stage: test
  image: $IMAGE
  script:
    - make security

sast:
  stage: security
include:
- template: Security/SAST.gitlab-ci.yml
