# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- quality_check
- test
- security
- build

variables:
  IMAGE_NAME: celebrity-ai
  IMAGE_TAG: v1.0.0
  LATEST: latest


include:
  - project: 'DATAKORI/ops/ci-templates'
    file: 'pipeline.yml'

build_image:
  stage: build
  image: docker:26.0.0-rc2-cli

  services:
    - docker:26.0.0-rc2-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo $REGISTRY_ACCESS_KEY | docker login -u $REGISTRY_USER --password-stdin
    - cd ./celebrity_recognition_ai/app/

  script:
    # Docker Hub
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$LATEST
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$LATEST

  after_script:
    - docker logout
