services:
  celebrity:
    image: $IMAGE_NAME:$IMAGE_TAG #TODO: PASS TAG TO docker compose command
    container_name: celebrity
    ports:
      - "$SERVER_PORT:$CONTAINER_PORT"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`celebrity.dev.datakori.tech`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"

  networks:
    proxy:
      external: true